// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /home/minyeonc/Desktop/Code/./Tryit.h;
#pragma link C++ defined_in "/home/minyeonc/Desktop/Code/./Tryit.C";

#endif
